version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5437:5432"
    volumes:
      - data:/var/lib/postgresql/data
     

    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
     - storage:/storage
volumes:
  data:
  storage:
    # external: true